from unittest import TestCase

from d08p1 import d08p1
from d08p1 import readDataFile as readP1Data
from d08p2 import d08p2
from d08p2 import readDataFile as readP2Data


class Day08_Test(TestCase):
    def test_part1_example(self):
        data = '''............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............'''
        self.assertEqual(d08p1(data), 14)

    def test_part1_solution(self):
        data = readP1Data()
        self.assertEqual(d08p1(data), 400)
    
    def test_part2_example(self):
        data = '''............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............'''
        self.assertEqual(d08p2(data), 34)
    
    def test_part2_solution(self):
        data = readP2Data()
        self.assertEqual(d08p2(data), 1280)
